name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: dmytrobudnik/worker-service:${{ env.IMAGE_TAG }}

      - name: Checkout k8s-infra repo
        uses: actions/checkout@v3
        with:
          repository: vivaDmytro/k8s-infra
          path: k8s-infra
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          ref: main

      - name: Update Helm chart image tag
        run: |
          sed -i "s|tag: .*|tag: \"${IMAGE_TAG}\"|" k8s-infra/charts/worker-service/values.yaml

      - name: Commit and push changes
        run: |
          cd k8s-infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/worker-service/values.yaml
          git commit -m "Update worker-service image tag to ${IMAGE_TAG}" || echo "No changes to commit"
          git push origin main
